
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;


namespace cfg
{
public sealed partial class DRCardPile : Luban.BeanBase
{
    public DRCardPile(ByteBuf _buf) 
    {
        Id = _buf.ReadInt();
        Skill = (ESkill)_buf.ReadInt();
        CardPile = (ECardPile)_buf.ReadInt();
    }

    public static DRCardPile DeserializeDRCardPile(ByteBuf _buf)
    {
        return new DRCardPile(_buf);
    }

    /// <summary>
    /// 编号
    /// </summary>
    public readonly int Id;
    /// <summary>
    /// 卡牌技能
    /// </summary>
    public readonly ESkill Skill;
    /// <summary>
    /// 所属牌堆
    /// </summary>
    public readonly ECardPile CardPile;
   
    public const int __ID__ = 1690855184;
    public override int GetTypeId() => __ID__;

    public  void ResolveRef(Tables tables)
    {
    }

    public override string ToString()
    {
        return "{ "
        + "Id:" + Id + ","
        + "Skill:" + Skill + ","
        + "CardPile:" + CardPile + ","
        + "}";
    }
}

}

