
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;


namespace cfg
{
public sealed partial class DRHero : Luban.BeanBase
{
    public DRHero(ByteBuf _buf) 
    {
        Id = _buf.ReadInt();
        {int n0 = System.Math.Min(_buf.ReadSize(), _buf.Size);Skill = new System.Collections.Generic.List<ESkill>(n0);for(var i0 = 0 ; i0 < n0 ; i0++) { ESkill _e0;  _e0 = (ESkill)_buf.ReadInt(); Skill.Add(_e0);}}
        HandLimit = _buf.ReadInt();
        HpLimit = _buf.ReadInt();
    }

    public static DRHero DeserializeDRHero(ByteBuf _buf)
    {
        return new DRHero(_buf);
    }

    /// <summary>
    /// 编号
    /// </summary>
    public readonly int Id;
    /// <summary>
    /// 技能列表
    /// </summary>
    public readonly System.Collections.Generic.List<ESkill> Skill;
    /// <summary>
    /// 手牌上限
    /// </summary>
    public readonly int HandLimit;
    /// <summary>
    /// 血量上限
    /// </summary>
    public readonly int HpLimit;
   
    public const int __ID__ = 2024756648;
    public override int GetTypeId() => __ID__;

    public  void ResolveRef(Tables tables)
    {
    }

    public override string ToString()
    {
        return "{ "
        + "Id:" + Id + ","
        + "Skill:" + Luban.StringUtil.CollectionToString(Skill) + ","
        + "HandLimit:" + HandLimit + ","
        + "HpLimit:" + HpLimit + ","
        + "}";
    }
}

}

