
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;



public partial class DTCardPile
{
    private readonly System.Collections.Generic.Dictionary<int, DRCardPile> _dataMap;
    private readonly System.Collections.Generic.List<DRCardPile> _dataList;
    
    public DTCardPile(ByteBuf _buf)
    {
        _dataMap = new System.Collections.Generic.Dictionary<int, DRCardPile>();
        _dataList = new System.Collections.Generic.List<DRCardPile>();
        
        for(int n = _buf.ReadSize() ; n > 0 ; --n)
        {
            DRCardPile _v;
            _v = global::DRCardPile.DeserializeDRCardPile(_buf);
            _dataList.Add(_v);
            _dataMap.Add(_v.Id, _v);
        }
    }

    public System.Collections.Generic.Dictionary<int, DRCardPile> DataMap => _dataMap;
    public System.Collections.Generic.List<DRCardPile> DataList => _dataList;

    public DRCardPile GetOrDefault(int key) => _dataMap.TryGetValue(key, out var v) ? v : null;
    public DRCardPile Get(int key) => _dataMap[key];
    public DRCardPile this[int key] => _dataMap[key];

    public void ResolveRef(Tables tables)
    {
        foreach(var _v in _dataList)
        {
            _v.ResolveRef(tables);
        }
    }

}



