
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;



public partial class DTCardConfig
{
    private readonly System.Collections.Generic.Dictionary<int, DRCardConfig> _dataMap;
    private readonly System.Collections.Generic.List<DRCardConfig> _dataList;
    
    public DTCardConfig(ByteBuf _buf)
    {
        _dataMap = new System.Collections.Generic.Dictionary<int, DRCardConfig>();
        _dataList = new System.Collections.Generic.List<DRCardConfig>();
        
        for(int n = _buf.ReadSize() ; n > 0 ; --n)
        {
            DRCardConfig _v;
            _v = global::DRCardConfig.DeserializeDRCardConfig(_buf);
            _dataList.Add(_v);
            _dataMap.Add(_v.Id, _v);
        }
    }

    public System.Collections.Generic.Dictionary<int, DRCardConfig> DataMap => _dataMap;
    public System.Collections.Generic.List<DRCardConfig> DataList => _dataList;

    public DRCardConfig GetOrDefault(int key) => _dataMap.TryGetValue(key, out var v) ? v : null;
    public DRCardConfig Get(int key) => _dataMap[key];
    public DRCardConfig this[int key] => _dataMap[key];

    public void ResolveRef(Tables tables)
    {
        foreach(var _v in _dataList)
        {
            _v.ResolveRef(tables);
        }
    }

}



