
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;


namespace cfg
{
public partial class DTHero
{
    private readonly System.Collections.Generic.Dictionary<int, DRHero> _dataMap;
    private readonly System.Collections.Generic.List<DRHero> _dataList;
    
    public DTHero(ByteBuf _buf)
    {
        _dataMap = new System.Collections.Generic.Dictionary<int, DRHero>();
        _dataList = new System.Collections.Generic.List<DRHero>();
        
        for(int n = _buf.ReadSize() ; n > 0 ; --n)
        {
            DRHero _v;
            _v = global::cfg.DRHero.DeserializeDRHero(_buf);
            _dataList.Add(_v);
            _dataMap.Add(_v.Id, _v);
        }
    }

    public System.Collections.Generic.Dictionary<int, DRHero> DataMap => _dataMap;
    public System.Collections.Generic.List<DRHero> DataList => _dataList;

    public DRHero GetOrDefault(int key) => _dataMap.TryGetValue(key, out var v) ? v : null;
    public DRHero Get(int key) => _dataMap[key];
    public DRHero this[int key] => _dataMap[key];

    public void ResolveRef(Tables tables)
    {
        foreach(var _v in _dataList)
        {
            _v.ResolveRef(tables);
        }
    }

}

}

