
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;


namespace cfg
{
public partial class DTOneConfig
{

     private readonly DROneConfig _data;

     public DROneConfig Data => _data;

    public DTOneConfig(ByteBuf _buf)
    {
        int n = _buf.ReadSize();
        if (n != 1) throw new SerializationException("table mode=one, but size != 1");
        _data = global::cfg.DROneConfig.DeserializeDROneConfig(_buf);
    }


    /// <summary>
    /// 匹配最大时间
    /// </summary>
     public int Test => _data.Test;
    
    public void ResolveRef(Tables tables)
    {
        _data.ResolveRef(tables);
    }
}

}

