
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------



namespace cfg
{ 
    /// <summary>
    /// 卡牌属性
    /// </summary>
    public enum ECardAttr
    {
        /// <summary>
        /// 金
        /// </summary>
        Jin = 0,
        /// <summary>
        /// 木
        /// </summary>
        Mu = 1,
        /// <summary>
        /// 水
        /// </summary>
        Shui = 2,
        /// <summary>
        /// 火
        /// </summary>
        Huo = 3,
        /// <summary>
        /// 土
        /// </summary>
        Tu = 4,
    }

} 

