
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------



 
    public enum ESkill
    {
        /// <summary>
        /// 杀
        /// </summary>
        Sha = 0,
        /// <summary>
        /// 闪
        /// </summary>
        Shan = 1,
        /// <summary>
        /// 七进七出
        /// </summary>
        QiJinQiChu = 2,
        /// <summary>
        /// 单骑救主
        /// </summary>
        DanQiJiuZhu = 3,
    }

 

