
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------



namespace cfg
{ 
    public enum ESkill
    {
        /// <summary>
        /// 斩
        /// </summary>
        Zhan = 0,
        /// <summary>
        /// 扫
        /// </summary>
        Sao = 1,
        /// <summary>
        /// 刺
        /// </summary>
        Ci = 2,
        /// <summary>
        /// 打
        /// </summary>
        Da = 3,
        /// <summary>
        /// 闪
        /// </summary>
        Shan = 4,
        /// <summary>
        /// 七进七出
        /// </summary>
        QiJinQiChu = 5,
        /// <summary>
        /// 单骑救主
        /// </summary>
        DanQiJiuZhu = 6,
    }

} 

