// This is automatically generated by CodeBind. Please do not modify it.

namespace Game.Hot
{
    public partial class HeroCardWidget : CodeBind.ICSCodeBind
    {
        public CodeBind.CSCodeBindMono Mono { get; private set; }
        public UnityEngine.Transform Transform { get; private set; }

        public TMPro.TMP_Text HandCardTMPText { get; private set; }
        public TMPro.TMP_Text HeroNameTMPText { get; private set; }
        public TMPro.TMP_Text HpTMPText { get; private set; }


        public void InitBind(CodeBind.CSCodeBindMono mono)
        {
            Mono = mono;
            Transform = mono.transform;
            HandCardTMPText = Mono.BindComponents[0] as TMPro.TMP_Text;
            HeroNameTMPText = Mono.BindComponents[1] as TMPro.TMP_Text;
            HpTMPText = Mono.BindComponents[2] as TMPro.TMP_Text;
        }

        public void ClearBind()
        {
            Mono = null;
            Transform = null;
            HandCardTMPText = null;
            HeroNameTMPText = null;
            HpTMPText = null;
        }
    }
}
