// This is automatically generated by CodeBind. Please do not modify it.

namespace Game.Hot
{
    public partial class BattleForm : CodeBind.ICSCodeBind
    {
        public CodeBind.CSCodeBindMono Mono { get; private set; }
        public UnityEngine.Transform Transform { get; private set; }

        public Game.AUIElement EnemyHeroCardUIElement { get; private set; }
        public Game.AUIElement MyHeroCardUIElement { get; private set; }


        public void InitBind(CodeBind.CSCodeBindMono mono)
        {
            Mono = mono;
            Transform = mono.transform;
            EnemyHeroCardUIElement = Mono.BindComponents[0] as Game.AUIElement;
            MyHeroCardUIElement = Mono.BindComponents[1] as Game.AUIElement;
        }

        public void ClearBind()
        {
            Mono = null;
            Transform = null;
            EnemyHeroCardUIElement = null;
            MyHeroCardUIElement = null;
        }
    }
}
