// This is automatically generated by CodeBind. Please do not modify it.

namespace Game.Hot
{
    public partial class LoginForm : CodeBind.ICSCodeBind
    {
        public CodeBind.CSCodeBindMono Mono { get; private set; }
        public UnityEngine.Transform Transform { get; private set; }

        public TMPro.TMP_Text accountIdTMPText { get; private set; }
        public UnityEngine.UI.Button sureButton { get; private set; }


        public void InitBind(CodeBind.CSCodeBindMono mono)
        {
            Mono = mono;
            Transform = mono.transform;
            accountIdTMPText = Mono.BindComponents[0] as TMPro.TMP_Text;
            sureButton = Mono.BindComponents[1] as UnityEngine.UI.Button;
        }

        public void ClearBind()
        {
            Mono = null;
            Transform = null;
            accountIdTMPText = null;
            sureButton = null;
        }
    }
}
