// This is automatically generated by CodeBind. Please do not modify it.

namespace Game.Hot
{
    public partial class LoginForm : CodeBind.ICSCodeBind
    {
        public CodeBind.CSCodeBindMono Mono { get; private set; }
        public UnityEngine.Transform Transform { get; private set; }

        public TMPro.TMP_Text AccountIdTMPText { get; private set; }
        public UnityEngine.UI.Button SureButton { get; private set; }


        public void InitBind(CodeBind.CSCodeBindMono mono)
        {
            Mono = mono;
            Transform = mono.transform;
            AccountIdTMPText = Mono.BindComponents[0] as TMPro.TMP_Text;
            SureButton = Mono.BindComponents[1] as UnityEngine.UI.Button;
        }

        public void ClearBind()
        {
            Mono = null;
            Transform = null;
            AccountIdTMPText = null;
            SureButton = null;
        }
    }
}
