// This is automatically generated by CodeBind. Please do not modify it.

namespace Game.Hot
{
    public partial class LoadingForm : CodeBind.ICSCodeBind
    {
        public CodeBind.CSCodeBindMono Mono { get; private set; }
        public UnityEngine.Transform Transform { get; private set; }

        public UnityEngine.UI.UXImage ProgressUXImage { get; private set; }
        public TMPro.TMP_Text TipTMPText { get; private set; }


        public void InitBind(CodeBind.CSCodeBindMono mono)
        {
            Mono = mono;
            Transform = mono.transform;
            ProgressUXImage = Mono.BindComponents[0] as UnityEngine.UI.UXImage;
            TipTMPText = Mono.BindComponents[1] as TMPro.TMP_Text;
        }

        public void ClearBind()
        {
            Mono = null;
            Transform = null;
            ProgressUXImage = null;
            TipTMPText = null;
        }
    }
}
