// This is automatically generated by CodeBind. Please do not modify it.

namespace Game.Hot
{
    public partial class ProgressBarElement : CodeBind.ICSCodeBind
    {
        public CodeBind.CSCodeBindMono Mono { get; private set; }
        public UnityEngine.Transform Transform { get; private set; }

        public UnityEngine.UI.UXImage CountDownUXImage { get; private set; }


        public void InitBind(CodeBind.CSCodeBindMono mono)
        {
            Mono = mono;
            Transform = mono.transform;
            CountDownUXImage = Mono.BindComponents[0] as UnityEngine.UI.UXImage;
        }

        public void ClearBind()
        {
            Mono = null;
            Transform = null;
            CountDownUXImage = null;
        }
    }
}
