// This is automatically generated by CodeBind. Please do not modify it.

namespace Game.Hot
{
    public partial class RoomForm : CodeBind.ICSCodeBind
    {
        public CodeBind.CSCodeBindMono Mono { get; private set; }
        public UnityEngine.Transform Transform { get; private set; }

        public TMPro.TMP_Text Player1TMPText { get; private set; }
        public TMPro.TMP_Text Player2TMPText { get; private set; }
        public UnityEngine.UI.Button StartGameButton { get; private set; }
        public UnityEngine.UI.UXImage StartGameUXImage { get; private set; }
        public UnityEngine.UI.UXImage State1UXImage { get; private set; }
        public UnityEngine.UI.UXImage State2UXImage { get; private set; }


        public void InitBind(CodeBind.CSCodeBindMono mono)
        {
            Mono = mono;
            Transform = mono.transform;
            Player1TMPText = Mono.BindComponents[0] as TMPro.TMP_Text;
            Player2TMPText = Mono.BindComponents[1] as TMPro.TMP_Text;
            StartGameButton = Mono.BindComponents[2] as UnityEngine.UI.Button;
            StartGameUXImage = Mono.BindComponents[3] as UnityEngine.UI.UXImage;
            State1UXImage = Mono.BindComponents[4] as UnityEngine.UI.UXImage;
            State2UXImage = Mono.BindComponents[5] as UnityEngine.UI.UXImage;
        }

        public void ClearBind()
        {
            Mono = null;
            Transform = null;
            Player1TMPText = null;
            Player2TMPText = null;
            StartGameButton = null;
            StartGameUXImage = null;
            State1UXImage = null;
            State2UXImage = null;
        }
    }
}
