// This is automatically generated by CodeBind. Please do not modify it.

namespace Game.Hot
{
    public partial class ChooseHeroForm : CodeBind.ICSCodeBind
    {
        public CodeBind.CSCodeBindMono Mono { get; private set; }
        public UnityEngine.Transform Transform { get; private set; }

        public Game.AUIElement HeroCardUIElement { get; private set; }
        public Game.AUIElement HeroCard1UIElement { get; private set; }
        public Game.AUIElement HeroCard2UIElement { get; private set; }
        public Game.AUIElement HeroCard3UIElement { get; private set; }
        public Game.AUIElement ProgressBarUIElement { get; private set; }


        public void InitBind(CodeBind.CSCodeBindMono mono)
        {
            Mono = mono;
            Transform = mono.transform;
            HeroCardUIElement = Mono.BindComponents[0] as Game.AUIElement;
            HeroCard1UIElement = Mono.BindComponents[1] as Game.AUIElement;
            HeroCard2UIElement = Mono.BindComponents[2] as Game.AUIElement;
            HeroCard3UIElement = Mono.BindComponents[3] as Game.AUIElement;
            ProgressBarUIElement = Mono.BindComponents[4] as Game.AUIElement;
        }

        public void ClearBind()
        {
            Mono = null;
            Transform = null;
            HeroCardUIElement = null;
            HeroCard1UIElement = null;
            HeroCard2UIElement = null;
            HeroCard3UIElement = null;
            ProgressBarUIElement = null;
        }
    }
}
