
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;

namespace Game.Hot
{
public sealed partial class DRCardConfig : Luban.BeanBase
{
    public DRCardConfig(ByteBuf _buf) 
    {
        Id = _buf.ReadInt();
        CardSkill = (ESkill)_buf.ReadInt();
        CardName = _buf.ReadString();
        PostInit();
    }

    public static DRCardConfig DeserializeDRCardConfig(ByteBuf _buf)
    {
        return new DRCardConfig(_buf);
    }

    /// <summary>
    /// 编号
    /// </summary>
    public readonly int Id;
    /// <summary>
    /// 卡牌技能
    /// </summary>
    public readonly ESkill CardSkill;
    /// <summary>
    /// 卡牌名字
    /// </summary>
    public readonly string CardName;
    public const int __ID__ = 1047620000;
    public override int GetTypeId() => __ID__;

    public  void ResolveRef(TablesComponent tables)
    {
        PostResolveRef();
    }

    public override string ToString()
    {
        return "{ "
        + "Id:" + Id + ","
        + "CardSkill:" + CardSkill + ","
        + "CardName:" + CardName + ","
        + "}";
    }

    partial void PostInit();
    partial void PostResolveRef();
}
}
