
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;

namespace Game.Hot
{
public sealed partial class DRCardPile : Luban.BeanBase
{
    public DRCardPile(ByteBuf _buf) 
    {
        Id = _buf.ReadInt();
        CardPile = (ECardPile)_buf.ReadInt();
        CardConfig = _buf.ReadInt();
        CardConfig_Ref = null;
        Num = _buf.ReadInt();
        CardAttr = (ECardAttr)_buf.ReadInt();
        PostInit();
    }

    public static DRCardPile DeserializeDRCardPile(ByteBuf _buf)
    {
        return new DRCardPile(_buf);
    }

    /// <summary>
    /// 编号
    /// </summary>
    public readonly int Id;
    /// <summary>
    /// 所属牌堆
    /// </summary>
    public readonly ECardPile CardPile;
    /// <summary>
    /// 卡牌配置
    /// </summary>
    public readonly int CardConfig;
    public DRCardConfig CardConfig_Ref { private set; get; }
    /// <summary>
    /// 点数
    /// </summary>
    public readonly int Num;
    /// <summary>
    /// 属性
    /// </summary>
    public readonly ECardAttr CardAttr;
    public const int __ID__ = 1690855184;
    public override int GetTypeId() => __ID__;

    public  void ResolveRef(TablesComponent tables)
    {
        CardConfig_Ref = tables.DTCardConfig.GetOrDefault(CardConfig);
        PostResolveRef();
    }

    public override string ToString()
    {
        return "{ "
        + "Id:" + Id + ","
        + "CardPile:" + CardPile + ","
        + "CardConfig:" + CardConfig + ","
        + "Num:" + Num + ","
        + "CardAttr:" + CardAttr + ","
        + "}";
    }

    partial void PostInit();
    partial void PostResolveRef();
}
}
