
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;

namespace Game.Hot
{
public sealed partial class DRHero : Luban.BeanBase
{
    public DRHero(ByteBuf _buf) 
    {
        Id = _buf.ReadInt();
        Name = _buf.ReadString();
        {int n0 = System.Math.Min(_buf.ReadSize(), _buf.Size);Skill = new System.Collections.Generic.List<ESkill>(n0);for(var i0 = 0 ; i0 < n0 ; i0++) { ESkill _e0;  _e0 = (ESkill)_buf.ReadInt(); Skill.Add(_e0);}}
        PostInit();
    }

    public static DRHero DeserializeDRHero(ByteBuf _buf)
    {
        return new DRHero(_buf);
    }

    /// <summary>
    /// 编号
    /// </summary>
    public readonly int Id;
    /// <summary>
    /// 名称
    /// </summary>
    public readonly string Name;
    /// <summary>
    /// 技能列表
    /// </summary>
    public readonly System.Collections.Generic.List<ESkill> Skill;
    public const int __ID__ = 2024756648;
    public override int GetTypeId() => __ID__;

    public  void ResolveRef(TablesComponent tables)
    {
        PostResolveRef();
    }

    public override string ToString()
    {
        return "{ "
        + "Id:" + Id + ","
        + "Name:" + Name + ","
        + "Skill:" + Luban.StringUtil.CollectionToString(Skill) + ","
        + "}";
    }

    partial void PostInit();
    partial void PostResolveRef();
}
}
