
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------



namespace Game.Hot
{ 
    /// <summary>
    /// 所属牌堆
    /// </summary>
    public enum ECardPile
    {
        /// <summary>
        /// 基础牌堆
        /// </summary>
        Base = 0,
    }

} 

