
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------



namespace Game.Hot
{ 
    public enum ESkill
    {
        /// <summary>
        /// 七进七出
        /// </summary>
        QiJinQiChu = 0,
        /// <summary>
        /// 单骑救主
        /// </summary>
        DanQiJiuZhu = 1,
    }

} 

