
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;

namespace Game.Hot
{
public partial class DTWeapon1 : IDataTable
{
    private readonly System.Collections.Generic.Dictionary<int, DRWeapon1> _dataMap;
    private readonly System.Collections.Generic.List<DRWeapon1> _dataList;
    private readonly System.Func<Cysharp.Threading.Tasks.UniTask<ByteBuf>> _loadFunc;

    public DTWeapon1(System.Func<Cysharp.Threading.Tasks.UniTask<ByteBuf>> loadFunc)
    {
        _loadFunc = loadFunc;
        _dataMap = new System.Collections.Generic.Dictionary<int, DRWeapon1>();
        _dataList = new System.Collections.Generic.List<DRWeapon1>();
    }

    public async Cysharp.Threading.Tasks.UniTask LoadAsync()
    {
        ByteBuf _buf = await _loadFunc();
        _dataMap.Clear();
        _dataList.Clear();
        for(int n = _buf.ReadSize() ; n > 0 ; --n)
        {
            DRWeapon1 _v;
            _v = global::Game.Hot.DRWeapon1.DeserializeDRWeapon1(_buf);
            _dataList.Add(_v);
            _dataMap.Add(_v.Id, _v);
        }
        PostInit();
    }

    public System.Collections.Generic.Dictionary<int, DRWeapon1> DataMap => _dataMap;
    public System.Collections.Generic.List<DRWeapon1> DataList => _dataList;
    public DRWeapon1 GetOrDefault(int key) => _dataMap.TryGetValue(key, out var v) ? v : null;
    public DRWeapon1 Get(int key) => _dataMap[key];
    public DRWeapon1 this[int key] => _dataMap[key];

    public void ResolveRef(Tables tables)
    {
        foreach(var _v in _dataList)
        {
            _v.ResolveRef(tables);
        }
        PostResolveRef();
    }


    partial void PostInit();
    partial void PostResolveRef();
}
}
