
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System.Collections.Generic;
using SimpleJSON;
using Luban;

namespace Game.Hot.Editor
{

public sealed class DRCardConfig :  Luban.EditorBeanBase 
{
    public DRCardConfig()
    {
            CardSkill = ESkill.Sha;
            CardName = "";
    }

    public override void LoadJson(SimpleJSON.JSONObject _json)
    {
        { 
            var _fieldJson = _json["Id"];
            if (_fieldJson != null)
            {
                if(!_fieldJson.IsNumber) { throw new SerializationException(); }  Id = _fieldJson;
            }
        }
        
        { 
            var _fieldJson = _json["CardSkill"];
            if (_fieldJson != null)
            {
                if(_fieldJson.IsString) { CardSkill = (ESkill)System.Enum.Parse(typeof(ESkill), _fieldJson); } else if(_fieldJson.IsNumber) { CardSkill = (ESkill)(int)_fieldJson; } else { throw new SerializationException(); }  
            }
        }
        
        { 
            var _fieldJson = _json["CardName"];
            if (_fieldJson != null)
            {
                if(!_fieldJson.IsString) { throw new SerializationException(); }  CardName = _fieldJson;
            }
        }
        
    }

    public override void SaveJson(SimpleJSON.JSONObject _json)
    {
        {
            _json["Id"] = new JSONNumber(Id);
        }
        {
            _json["CardSkill"] = new JSONNumber((int)CardSkill);
        }
        {

            if (CardName == null) { throw new System.ArgumentNullException(); }
            _json["CardName"] = new JSONString(CardName);
        }
    }

    public static DRCardConfig LoadJsonDRCardConfig(SimpleJSON.JSONNode _json)
    {
        DRCardConfig obj = new DRCardConfig();
        obj.LoadJson((SimpleJSON.JSONObject)_json);
        return obj;
    }
        
    public static void SaveJsonDRCardConfig(DRCardConfig _obj, SimpleJSON.JSONNode _json)
    {
        _obj.SaveJson((SimpleJSON.JSONObject)_json);
    }

    /// <summary>
    /// 编号
    /// </summary>
    public int Id;

    /// <summary>
    /// 卡牌技能
    /// </summary>
    public ESkill CardSkill;

    /// <summary>
    /// 卡牌名字
    /// </summary>
    public string CardName;

}

}

