
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System.Collections.Generic;
using SimpleJSON;
using Luban;

namespace Game.Hot.Editor
{

public sealed class DRHero :  Luban.EditorBeanBase 
{
    public DRHero()
    {
            Name = "";
            Skill = new System.Collections.Generic.List<ESkill>();
    }

    public override void LoadJson(SimpleJSON.JSONObject _json)
    {
        { 
            var _fieldJson = _json["Id"];
            if (_fieldJson != null)
            {
                if(!_fieldJson.IsNumber) { throw new SerializationException(); }  Id = _fieldJson;
            }
        }
        
        { 
            var _fieldJson = _json["Name"];
            if (_fieldJson != null)
            {
                if(!_fieldJson.IsString) { throw new SerializationException(); }  Name = _fieldJson;
            }
        }
        
        { 
            var _fieldJson = _json["Skill"];
            if (_fieldJson != null)
            {
                if(!_fieldJson.IsArray) { throw new SerializationException(); } Skill = new System.Collections.Generic.List<ESkill>(); foreach(JSONNode __e0 in _fieldJson.Children) { ESkill __v0;  if(__e0.IsString) { __v0 = (ESkill)System.Enum.Parse(typeof(ESkill), __e0); } else if(__e0.IsNumber) { __v0 = (ESkill)(int)__e0; } else { throw new SerializationException(); }    Skill.Add(__v0); }  
            }
        }
        
    }

    public override void SaveJson(SimpleJSON.JSONObject _json)
    {
        {
            _json["Id"] = new JSONNumber(Id);
        }
        {

            if (Name == null) { throw new System.ArgumentNullException(); }
            _json["Name"] = new JSONString(Name);
        }
        {

            if (Skill == null) { throw new System.ArgumentNullException(); }
            { var __cjson0 = new JSONArray(); _json["Skill"] = __cjson0; foreach(var _e0 in Skill) { JSONNode __v0; __v0 = new JSONNumber((int)_e0); __cjson0.Add(__v0); } }
        }
    }

    public static DRHero LoadJsonDRHero(SimpleJSON.JSONNode _json)
    {
        DRHero obj = new DRHero();
        obj.LoadJson((SimpleJSON.JSONObject)_json);
        return obj;
    }
        
    public static void SaveJsonDRHero(DRHero _obj, SimpleJSON.JSONNode _json)
    {
        _obj.SaveJson((SimpleJSON.JSONObject)_json);
    }

    /// <summary>
    /// 编号
    /// </summary>
    public int Id;

    /// <summary>
    /// 名称
    /// </summary>
    public string Name;

    /// <summary>
    /// 技能列表
    /// </summary>
    public System.Collections.Generic.List<ESkill> Skill;

}

}

