
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace Game.Hot.Editor
{
    /// <summary>
    /// 卡牌属性
    /// </summary>
    public enum ECardAttr
    {
        /// <summary>
        /// 金
        /// </summary>
        Jin = 0,
        /// <summary>
        /// 木
        /// </summary>
        Mu = 1,
        /// <summary>
        /// 水
        /// </summary>
        Shui = 2,
        /// <summary>
        /// 火
        /// </summary>
        Huo = 3,
        /// <summary>
        /// 土
        /// </summary>
        Tu = 4,
    }

    public static class ECardAttr_Metadata
    {
        public static readonly Luban.EditorEnumItemInfo Jin = new Luban.EditorEnumItemInfo("Jin", "金", 0, "金");
        public static readonly Luban.EditorEnumItemInfo Mu = new Luban.EditorEnumItemInfo("Mu", "木", 1, "木");
        public static readonly Luban.EditorEnumItemInfo Shui = new Luban.EditorEnumItemInfo("Shui", "水", 2, "水");
        public static readonly Luban.EditorEnumItemInfo Huo = new Luban.EditorEnumItemInfo("Huo", "火", 3, "火");
        public static readonly Luban.EditorEnumItemInfo Tu = new Luban.EditorEnumItemInfo("Tu", "土", 4, "土");

        private static readonly System.Collections.Generic.List<Luban.EditorEnumItemInfo> __items = new System.Collections.Generic.List<Luban.EditorEnumItemInfo>
        {
            Jin,
            Mu,
            Shui,
            Huo,
            Tu,
        };

        public static System.Collections.Generic.List<Luban.EditorEnumItemInfo> GetItems() => __items;

        public static Luban.EditorEnumItemInfo GetByName(string name)
        {
            return __items.Find(c => c.Name == name);
        }

        public static Luban.EditorEnumItemInfo GetByNameOrAlias(string name)
        {
            return __items.Find(c => c.Name == name || c.Alias == name);
        }

        public static Luban.EditorEnumItemInfo GetByValue(int value)
        {
            return __items.Find(c => c.Value == value);
        }
    }

} 

