
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace Game.Hot.Editor
{
    public enum ESkill
    {
        /// <summary>
        /// 七进七出
        /// </summary>
        QiJinQiChu = 0,
        /// <summary>
        /// 单骑救主
        /// </summary>
        DanQiJiuZhu = 1,
    }

    public static class ESkill_Metadata
    {
        public static readonly Luban.EditorEnumItemInfo QiJinQiChu = new Luban.EditorEnumItemInfo("QiJinQiChu", "七进七出", 0, "七进七出");
        public static readonly Luban.EditorEnumItemInfo DanQiJiuZhu = new Luban.EditorEnumItemInfo("DanQiJiuZhu", "单骑救主", 1, "单骑救主");

        private static readonly System.Collections.Generic.List<Luban.EditorEnumItemInfo> __items = new System.Collections.Generic.List<Luban.EditorEnumItemInfo>
        {
            QiJinQiChu,
            DanQiJiuZhu,
        };

        public static System.Collections.Generic.List<Luban.EditorEnumItemInfo> GetItems() => __items;

        public static Luban.EditorEnumItemInfo GetByName(string name)
        {
            return __items.Find(c => c.Name == name);
        }

        public static Luban.EditorEnumItemInfo GetByNameOrAlias(string name)
        {
            return __items.Find(c => c.Name == name || c.Alias == name);
        }

        public static Luban.EditorEnumItemInfo GetByValue(int value)
        {
            return __items.Find(c => c.Value == value);
        }
    }

} 

