// This is automatically generated by CodeBind. Please do not modify it.

namespace Game.Hot
{
    public partial class BattleCardUIElement : CodeBind.ICSCodeBind
    {
        public CodeBind.CSCodeBindMono Mono { get; private set; }
        public UnityEngine.Transform Transform { get; private set; }

        public UnityEngine.UI.Button CardBgButton { get; private set; }
        public TMPro.TMP_Text CardInfoTMPText { get; private set; }
        public TMPro.TMP_Text CardNameTMPText { get; private set; }


        public void InitBind(CodeBind.CSCodeBindMono mono)
        {
            Mono = mono;
            Transform = mono.transform;
            CardBgButton = Mono.BindComponents[0] as UnityEngine.UI.Button;
            CardInfoTMPText = Mono.BindComponents[1] as TMPro.TMP_Text;
            CardNameTMPText = Mono.BindComponents[2] as TMPro.TMP_Text;
        }

        public void ClearBind()
        {
            Mono = null;
            Transform = null;
            CardBgButton = null;
            CardInfoTMPText = null;
            CardNameTMPText = null;
        }
    }
}
