// This is automatically generated by CodeBind. Please do not modify it.

namespace Game.Hot
{
    public partial class SelectHeroForm : CodeBind.ICSCodeBind
    {
        public CodeBind.CSCodeBindMono Mono { get; private set; }
        public UnityEngine.Transform Transform { get; private set; }

        public TMPro.TMP_Text ChooseHeroTMPText { get; private set; }
        public TMPro.TMP_Text HeroName1TMPText { get; private set; }
        public TMPro.TMP_Text HeroName2TMPText { get; private set; }
        public Game.AUIWidget ProgressBarUIWidget { get; private set; }
        public UnityEngine.UI.Button Select1Button { get; private set; }
        public UnityEngine.UI.Button Select2Button { get; private set; }
        public UnityEngine.UI.UXImage State1UXImage { get; private set; }


        public void InitBind(CodeBind.CSCodeBindMono mono)
        {
            Mono = mono;
            Transform = mono.transform;
            ChooseHeroTMPText = Mono.BindComponents[0] as TMPro.TMP_Text;
            HeroName1TMPText = Mono.BindComponents[1] as TMPro.TMP_Text;
            HeroName2TMPText = Mono.BindComponents[2] as TMPro.TMP_Text;
            ProgressBarUIWidget = Mono.BindComponents[3] as Game.AUIWidget;
            Select1Button = Mono.BindComponents[4] as UnityEngine.UI.Button;
            Select2Button = Mono.BindComponents[5] as UnityEngine.UI.Button;
            State1UXImage = Mono.BindComponents[6] as UnityEngine.UI.UXImage;
        }

        public void ClearBind()
        {
            Mono = null;
            Transform = null;
            ChooseHeroTMPText = null;
            HeroName1TMPText = null;
            HeroName2TMPText = null;
            ProgressBarUIWidget = null;
            Select1Button = null;
            Select2Button = null;
            State1UXImage = null;
        }
    }
}
