// This is automatically generated by CodeBind. Please do not modify it.

namespace Game.Hot
{
    public partial class SelectHeroForm : CodeBind.ICSCodeBind
    {
        public CodeBind.CSCodeBindMono Mono { get; private set; }
        public UnityEngine.Transform Transform { get; private set; }

        public Game.AUIWidget HeroCardUIWidget { get; private set; }
        public Game.AUIWidget HeroCard1UIWidget { get; private set; }
        public Game.AUIWidget HeroCard2UIWidget { get; private set; }
        public Game.AUIWidget HeroCard3UIWidget { get; private set; }
        public Game.AUIWidget ProgressBarUIWidget { get; private set; }


        public void InitBind(CodeBind.CSCodeBindMono mono)
        {
            Mono = mono;
            Transform = mono.transform;
            HeroCardUIWidget = Mono.BindComponents[0] as Game.AUIWidget;
            HeroCard1UIWidget = Mono.BindComponents[1] as Game.AUIWidget;
            HeroCard2UIWidget = Mono.BindComponents[2] as Game.AUIWidget;
            HeroCard3UIWidget = Mono.BindComponents[3] as Game.AUIWidget;
            ProgressBarUIWidget = Mono.BindComponents[4] as Game.AUIWidget;
        }

        public void ClearBind()
        {
            Mono = null;
            Transform = null;
            HeroCardUIWidget = null;
            HeroCard1UIWidget = null;
            HeroCard2UIWidget = null;
            HeroCard3UIWidget = null;
            ProgressBarUIWidget = null;
        }
    }
}
